### PR TITLE
Usability/compatibility changes (more info inside)

### PR DESCRIPTION
**Pull request by clocklear**
Hi!

Thanks for an excellent library!  I've made a few usability tweaks to make this more friendly for others:
- **Makefile** -- this makes it more clearly defined how to do thing like build and test.  It also references NPM binaries that are installed in the project so that globally installed modules are not required (mocha, gulp)
- **component.json** -- this allows use of the module within Duo.
- Additionally, I tweaked the browserify build options in the gulpfile so that the module is exported UMD style -- this was another requirement for Duo.  The changes should be backwards compatible.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Good improvements! 

The only thing that is confuse for me is the Makefile. I don't know If I want to mixin Make with the project, because I identify Make command more with C/C++ projects, and, on the other hand, [npm support some userful scripts for do it](https://docs.npmjs.com/misc/scripts).

What do you think?

**Comment by clocklear** [comment]
npm scripts could be good.  I lean to Makefiles for everything (including node projects) so that habit tends to bleed over into other things.  If you don't want to introduce a Makefile, that's totally fine -- I can update the PR to use npm scripts instead.

**Comment by Kikobeats** [comment]
I think that extending `package.json` is enough. Putting another file for do the same just cause confusion.

If you can refactor the PR I will merged :-)

**Comment by clocklear** [comment]
PR updated.  While I understand why you have a shell script to run your tests, I would strongly suggest moving that command inside the `package.json` and referencing the local mocha binary that is installed with `npm i`.  This would allow someone to run your tests without having **mocha** installed globally.

**Comment by Kikobeats** [comment]
Good point, I updated the test file :+1:

I tried locally `dist/acho.js` and doesn't work. Browserify doesn't create correctly the package if you use `standalone` flag. Can you check it? If I delete the flags works fine, but I don't know if you has put the flag for something... 

when you modify the `gulp` file run `npm run-script build` and open `dist/example.html` and check in the console that all works fine!

**Comment by clocklear** [comment]
My apologies, **example.html** needs to change.  The **standalone** flag tells browserify to create a UMD compatible package.  When loaded in an environment that has `require` (like Node), the module can be required, as expected.  When loaded in a browser (where `require` doesn't natively exist), the module is leaked to the page as **Acho**.  Therefore, all you need to do in a browser is to create a `new Acho()`.  No require is needed.

More info can be found here: http://www.forbeslindesay.co.uk/post/46324645400/standalone-browserify-builds.

I've updated the build script (to properly name the module) and `example.html` in the PR.

**Comment by Kikobeats** [comment]
so now I don't understand why you want to expose as global object :sa: 

It's more secure juse instance when you need, and later use it. The problem that I'm trying to avoid using require declaration is have too many global objects in the frontend.

**Comment by clocklear** [comment]
It's not that I want a global object, at all.  That's just how example.html is written -- I mearly adapted it to work the way it was already working.  Browsers do not natively have a `require` system, so you should not require that your module be loaded with `require`.  That's not a compatible way to do things.  Your modules should be able to be loaded properly regardless of where they are requested.

If you were to use browserify to package another system that depends on Acho, it would **not** be leaked globally.  It would be self-contained within the scope of that application.

Take a look at this example I just whipped up:
http://embed.plnkr.co/wjKwxApGtHQpKrzcX5yX/preview

Notice that when using Acho as a component of larger application, an Acho global **does not** get leaked to the page.  The global scope does not get dirtied up.  That's why a UMD module is awesome -- it automatically does the correct thing based on how it is used.  If you can require it, it can be required.  If you cannot, it leaks a global.  This allows for the most compatibility with existing systems.

More UMD info can be found:
http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/

**Comment by clocklear** [comment]
Any thoughts here?

**Comment by Kikobeats** [comment]
Really I don't use UMD or AMD because packaged the modules using browserify and require in the browser is extremely simple, but I understand you.

The only thing is that I compiled again the module using `gulp` and is expose as global object, can you check?

If you need to capitalize the name use [titleize](https://www.npmjs.com/package/titleize), is more clear for maintain the package in the future.

The only thing is that in the example is a global object,

**Comment by clocklear** [comment]
Compiling the module and requiring it directly in the browser will always result in a global object.

If you require the module in a builder (webpack, duo, browserify), no global object will exist.

I'm sorry these changes go against the spirit of what you're trying to accomplish.  If this doesn't work for you, I can fork the project and make my own version.

**Comment by Kikobeats** [comment]
No, I prefer adapt my style and merge the PR, but I need to understand all workflows.

Please, Can you write a little of documentation in README.md about how to load the module in the browser for the different module loaders? to make it all clear

**Comment by clocklear** [comment]
Absolutely.  I'll get the `README.md` updated ASAP.

**Comment by clocklear** [comment]
`README.md`updated and switched to `titleize` in the gulp file.

**Comment by Kikobeats** [comment]
thanks! :-)

**Comment by Kikobeats** [comment]
@clocklear do you think that standalone setting in `gulpfile` is just because Acho is a class?

I have a [generator for git repositories](https://github.com/Kikobeats/generator-git/blob/master/app/templates/_gulpfile.coffee) and I'm thinking to update the code for the next time, but I don't sure if is a good point uses always `titleize` for prefix the module shortcut.

**Comment by clocklear** [comment]
Yes.  I `titleize`d the module name since it gets used as a class -- by convention.

**Pull request merged**
