### PR TITLE
Add chalk modifiers to message type

### PR DESCRIPTION
**Pull request by terox**
Hello,

This is a small improvement for use chalk modifiers (bold, italic...) in message type. May be it is useful for somebody.

Cheers!

### CODE REVIEW

**Comment by Kikobeats** [comment]
I'm understand what you are trying to express, but I think that can be more simple. Because chalk methods are chaineables, like:

``` js
chalk.blue.bgRed.bold('Hello world!');
```

Instead of create a container called `modifiers` and make the logic of the class more complex, we can extend the `color` for support different styles in the container. Just we have to separate the styles with spaces and process the string for be converted in the chalk API, for example:

``` coffee
color: 'bold red' 
```

can be converted in the chalk method `chalk['bold']['red'](message)`.

What do you think? :-)

**Comment by terox** [comment]
I think that it is the best solution. More natural. More smart. It's perfect.

**Comment by Kikobeats** [comment]
@terox I have already written, I'm fixing browserify build and I will tag the new version. soon! :-)

**Comment by terox** [comment]
Thank you for your time. I hope that it has helped a bit ;)

**Comment by Kikobeats** [comment]
@terox check it out! :)

**Comment by terox** [comment]
It works. It's fantastic! :)

**Pull request closed without merging**
